version: '3.8'
services:
  buildkite-agent:
    image: buildkite/agent:3
    environment:
      BUILDKITE_AGENT_TOKEN: "Poner-aqui-tu-token"
      BUILDKITE_AGENT_NAME: "Token-agente"
      BUILDKITE_AGENT_QUEUE: "default2"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./builds:/builds
